version: '3.7'

services:
  pglsql:
    container_name: pglsql_diploma
    ports:
        - "5432:5432"
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
        POSTGRES_DB: "diploma"
        POSTGRES_PASSWORD: "admin"
        POSTGRES_USER: "admin"
    volumes:
        - database_data:/var/lib/postgresql/data:rw
volumes:
  database_data:
