-- +goose Up
CREATE TABLE orders (
    id SERIAL PRIMARY KEY,
    user_id INTEGER DEFAULT NULL,
    number VARCHAR(20) UNIQUE NOT NULL,
    status VARCHAR(40) NOT NULL,
    accrual INTEGER DEFAULT 0,
    uploaded_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
ALTER TABLE orders ADD CONSTRAINT FK_USER_ORDERS FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
CREATE INDEX IDX_USER_ORDERS ON orders (user_Id);

-- +goose Down
ALTER TABLE orders DROP CONSTRAINT FK_USER_ORDERS;
DROP TABLE orders;
