// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/core/ports/order.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	ordersdto "github.com/bubaew95/yandex-diploma/internal/core/dto/response/ordersdto"
	systemdto "github.com/bubaew95/yandex-diploma/internal/core/dto/response/systemdto"
	orderentity "github.com/bubaew95/yandex-diploma/internal/core/entity/orderentity"
	ordersmodel "github.com/bubaew95/yandex-diploma/internal/core/model/ordersmodel"
	gomock "github.com/golang/mock/gomock"
)

// MockOrderService is a mock of OrderService interface.
type MockOrderService struct {
	ctrl     *gomock.Controller
	recorder *MockOrderServiceMockRecorder
}

// MockOrderServiceMockRecorder is the mock recorder for MockOrderService.
type MockOrderServiceMockRecorder struct {
	mock *MockOrderService
}

// NewMockOrderService creates a new mock instance.
func NewMockOrderService(ctrl *gomock.Controller) *MockOrderService {
	mock := &MockOrderService{ctrl: ctrl}
	mock.recorder = &MockOrderServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderService) EXPECT() *MockOrderServiceMockRecorder {
	return m.recorder
}

// AddOrdersNumber mocks base method.
func (m *MockOrderService) AddOrdersNumber(ctx context.Context, number string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddOrdersNumber", ctx, number)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddOrdersNumber indicates an expected call of AddOrdersNumber.
func (mr *MockOrderServiceMockRecorder) AddOrdersNumber(ctx, number interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddOrdersNumber", reflect.TypeOf((*MockOrderService)(nil).AddOrdersNumber), ctx, number)
}

// OrdersByUserID mocks base method.
func (m *MockOrderService) OrdersByUserID(ctx context.Context) ([]ordersdto.Orders, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OrdersByUserID", ctx)
	ret0, _ := ret[0].([]ordersdto.Orders)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OrdersByUserID indicates an expected call of OrdersByUserID.
func (mr *MockOrderServiceMockRecorder) OrdersByUserID(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OrdersByUserID", reflect.TypeOf((*MockOrderService)(nil).OrdersByUserID), ctx)
}

// OrdersWithoutAccrual mocks base method.
func (m *MockOrderService) OrdersWithoutAccrual(ctx context.Context) ([]orderentity.OrderDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OrdersWithoutAccrual", ctx)
	ret0, _ := ret[0].([]orderentity.OrderDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OrdersWithoutAccrual indicates an expected call of OrdersWithoutAccrual.
func (mr *MockOrderServiceMockRecorder) OrdersWithoutAccrual(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OrdersWithoutAccrual", reflect.TypeOf((*MockOrderService)(nil).OrdersWithoutAccrual), ctx)
}

// UpdateOrderByID mocks base method.
func (m *MockOrderService) UpdateOrderByID(ctx context.Context, userID int64, cs systemdto.CalculationSystem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrderByID", ctx, userID, cs)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOrderByID indicates an expected call of UpdateOrderByID.
func (mr *MockOrderServiceMockRecorder) UpdateOrderByID(ctx, userID, cs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrderByID", reflect.TypeOf((*MockOrderService)(nil).UpdateOrderByID), ctx, userID, cs)
}

// MockOrderRepository is a mock of OrderRepository interface.
type MockOrderRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOrderRepositoryMockRecorder
}

// MockOrderRepositoryMockRecorder is the mock recorder for MockOrderRepository.
type MockOrderRepositoryMockRecorder struct {
	mock *MockOrderRepository
}

// NewMockOrderRepository creates a new mock instance.
func NewMockOrderRepository(ctrl *gomock.Controller) *MockOrderRepository {
	mock := &MockOrderRepository{ctrl: ctrl}
	mock.recorder = &MockOrderRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderRepository) EXPECT() *MockOrderRepositoryMockRecorder {
	return m.recorder
}

// AddOrdersNumber mocks base method.
func (m *MockOrderRepository) AddOrdersNumber(ctx context.Context, order ordersmodel.Order) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddOrdersNumber", ctx, order)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddOrdersNumber indicates an expected call of AddOrdersNumber.
func (mr *MockOrderRepositoryMockRecorder) AddOrdersNumber(ctx, order interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddOrdersNumber", reflect.TypeOf((*MockOrderRepository)(nil).AddOrdersNumber), ctx, order)
}

// OrdersByUserID mocks base method.
func (m *MockOrderRepository) OrdersByUserID(ctx context.Context, userID int64) ([]ordersdto.Orders, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OrdersByUserID", ctx, userID)
	ret0, _ := ret[0].([]ordersdto.Orders)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OrdersByUserID indicates an expected call of OrdersByUserID.
func (mr *MockOrderRepositoryMockRecorder) OrdersByUserID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OrdersByUserID", reflect.TypeOf((*MockOrderRepository)(nil).OrdersByUserID), ctx, userID)
}

// OrdersWithoutAccrual mocks base method.
func (m *MockOrderRepository) OrdersWithoutAccrual(ctx context.Context) ([]orderentity.OrderDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OrdersWithoutAccrual", ctx)
	ret0, _ := ret[0].([]orderentity.OrderDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OrdersWithoutAccrual indicates an expected call of OrdersWithoutAccrual.
func (mr *MockOrderRepositoryMockRecorder) OrdersWithoutAccrual(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OrdersWithoutAccrual", reflect.TypeOf((*MockOrderRepository)(nil).OrdersWithoutAccrual), ctx)
}

// UpdateOrderByID mocks base method.
func (m *MockOrderRepository) UpdateOrderByID(ctx context.Context, userID int64, cs systemdto.CalculationSystem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrderByID", ctx, userID, cs)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOrderByID indicates an expected call of UpdateOrderByID.
func (mr *MockOrderRepositoryMockRecorder) UpdateOrderByID(ctx, userID, cs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrderByID", reflect.TypeOf((*MockOrderRepository)(nil).UpdateOrderByID), ctx, userID, cs)
}
